ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY STATIC_DATA_DIR
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE
    SKIP 1                                          -- skip the header row
    CHARACTERSET AL32UTF8
    BADFILE STATIC_DATA_LOG_DIR:'currency_codes.bad'
    LOGFILE STATIC_DATA_LOG_DIR:'currency_codes.log'
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    MISSING FIELD VALUES ARE NULL
    ( CODE, CURRENCY_NAME, DECIMAL_PLACES )
  )
  LOCATION ('currency_codes.csv')
)
REJECT LIMIT UNLIMITED;